"""
DimHierarchy Table Definition
Stores the hierarchy data
"""

TABLE = {
    "order": 4,
    "name": "dim_hierarchy",
    "schema": """CREATE TABLE dim_hierarchy (
                cluster_code VARCHAR(20),
                cluster_cost_center BIGINT,
                cluster_description VARCHAR(125),
                cluster_emp_code VARCHAR(100),
                cluster_emp_name VARCHAR(132),
                cluster_emp_position VARCHAR(136),
                cluster_mobile BIGINT,
                cluster_position INTEGER,
                created_date INTEGER,
                division_code SMALLINT,
                hs VARCHAR(100),
                mdi_01_a VARCHAR(100),
                mdi_01_b VARCHAR(100),
                mdi_01_c VARCHAR(100),
                mdi_01_d VARCHAR(107),
                primary_key VARCHAR(131),
                primary_key_value VARCHAR(157),
                product_code VARCHAR(112),
                product_name VARCHAR(143),
                sales_group SMALLINT,
                sh_2_code VARCHAR(107),
                sh_2_cost_center_code VARCHAR(107),
                sh_2_email VARCHAR(136),
                sh_2_emp_code VARCHAR(100),
                sh_2_emp_name VARCHAR(136),
                sh_2_emp_position INTEGER,
                sh_2_hq VARCHAR(124),
                sh_2_mobile VARCHAR(110),
                sh_2_name VARCHAR(140),
                sh_3_code VARCHAR(107),
                sh_3_cost_center_code BIGINT,
                sh_3_email VARCHAR(136),
                sh_3_emp_code VARCHAR(100),
                sh_3_emp_name VARCHAR(135),
                sh_3_emp_position INTEGER,
                sh_3_hq VARCHAR(128),
                sh_3_mobile BIGINT,
                sh_3_name VARCHAR(134),
                sh_4_code VARCHAR(107),
                sh_4_cost_center_code BIGINT,
                sh_4_email VARCHAR(133),
                sh_4_emp_code VARCHAR(100),
                sh_4_emp_name VARCHAR(130),
                sh_4_emp_position INTEGER,
                sh_4_hq VARCHAR(128),
                sh_4_mobile BIGINT,
                sh_4_name VARCHAR(134),
                sh_5_code VARCHAR(107),
                sh_5_cost_center_code BIGINT,
                sh_5_email VARCHAR(132),
                sh_5_emp_code VARCHAR(100),
                sh_5_emp_name VARCHAR(130),
                sh_5_emp_position INTEGER,
                sh_5_hq VARCHAR(128),
                sh_5_mobile BIGINT,
                sh_5_name VARCHAR(130),
                sh_6_code VARCHAR(107),
                sh_6_cost_center_code BIGINT,
                sh_6_email VARCHAR(132),
                sh_6_emp_code VARCHAR(100),
                sh_6_emp_name VARCHAR(124),
                sh_6_emp_position INTEGER,
                sh_6_hq VARCHAR(121),
                sh_6_mobile BIGINT,
                sh_6_name VARCHAR(127),
                sh_7_code VARCHAR(107),
                sh_7_cost_center_code BIGINT,
                sh_7_email VARCHAR(130),
                sh_7_emp_code VARCHAR(100),
                sh_7_emp_name VARCHAR(118),
                sh_7_emp_position INTEGER,
                sh_7_hq VARCHAR(121),
                sh_7_mobile BIGINT,
                sh_7_name VARCHAR(122),
                txn_type VARCHAR(145),
                wss_territory_code VARCHAR(107),
                wss_territory_name VARCHAR(130)
            )
            DISTRIBUTED BY HASH(cluster_code) BUCKETS 10
            PROPERTIES (
                "replication_num" = "1"
            );""",
    "comments": {
        "table": "Stores the hierarchy data.",
        "columns": {},
    },
}
