"""
DimMaterial Table Definition
Stores the material data
"""

TABLE = {
    "order": 6,
    "name": "dim_material",
    "indexes": {},
    "schema": """CREATE TABLE dim_material (
                active_flag VARCHAR(104),
                average_rate_case DOUBLE,
                average_rate_each DOUBLE,
                average_rate_kg DOUBLE,
                average_rate_litre DOUBLE,
                base_uom VARCHAR(103),
                base_uom_description VARCHAR(100),
                category_1 VARCHAR(104),
                category_2 VARCHAR(104),
                cati_ii VARCHAR(102),
                cgst_percent DOUBLE,
                cross_plant_material_status VARCHAR(102),
                cross_selling_indicator VARCHAR(101),
                current_dw_key VARCHAR(100),
                default_retail_flag SMALLINT,
                division_code SMALLINT,
                division_description VARCHAR(120),
                document_type VARCHAR(103),
                dw_key_product VARCHAR(100),
                ei_chairman_club_flag VARCHAR(101),
                fsn_category VARCHAR(101),
                fsn_description VARCHAR(121),
                gross_weight DOUBLE,
                hsn_code DOUBLE,
                hsn_description VARCHAR(120),
                igst_percent DOUBLE,
                material_code VARCHAR(118),
                material_description VARCHAR(140),
                material_group VARCHAR(107),
                material_group_1 SMALLINT,
                material_group_1_description VARCHAR(120),
                material_group_2 SMALLINT,
                material_group_2_description VARCHAR(120),
                material_group_description VARCHAR(120),
                material_type VARCHAR(104),
                material_type_description VARCHAR(125),
                material_valid_from INTEGER,
                material_valid_to INTEGER,
                maximum_retail_price DOUBLE,
                mother_code VARCHAR(118),
                mother_code_description VARCHAR(140),
                mother_material_average_rate_case DOUBLE,
                mother_material_average_rate_each DOUBLE,
                mother_material_average_rate_kg DOUBLE,
                mother_material_average_rate_litre DOUBLE,
                mrp_relevent VARCHAR(101),
                mrp_uom VARCHAR(103),
                net_weight DOUBLE,
                new_hsn_code VARCHAR(109),
                old_material_number VARCHAR(118),
                p_2_p_indicator VARCHAR(101),
                prd_group_1 VARCHAR(102),
                prd_group_2 VARCHAR(104),
                prd_group_3 VARCHAR(108),
                prd_group_4 VARCHAR(112),
                prd_group_5 VARCHAR(117),
                prd_group_security VARCHAR(147),
                price_to_retailer DOUBLE,
                price_valid_from INTEGER,
                price_valid_to INTEGER,
                product_group_1_description VARCHAR(140),
                product_group_2_description VARCHAR(140),
                product_group_3_description VARCHAR(140),
                product_group_4_description VARCHAR(140),
                product_group_5_description VARCHAR(131),
                product_group_6_description VARCHAR(122),
                product_group_description_security VARCHAR(254),
                ptr_uom VARCHAR(103),
                reason_code SMALLINT,
                reason_text VARCHAR(119),
                record_valid_from INTEGER,
                record_valid_to VARCHAR(100),
                reporting_unit VARCHAR(103),
                revised_shelf_life SMALLINT,
                sales_forecasting VARCHAR(101),
                sales_group_code SMALLINT,
                sales_organization_code SMALLINT,
                sales_unit VARCHAR(103),
                sales_unit_description VARCHAR(109),
                selling_price DOUBLE,
                sgst_percent DOUBLE,
                short_text VARCHAR(125),
                size_dimensions VARCHAR(131),
                spu_om VARCHAR(103),
                status_description VARCHAR(125),
                total_shelf_life_days SMALLINT,
                ugst_percent DOUBLE,
                volume DOUBLE,
                volume_unit VARCHAR(103),
                weight_unit VARCHAR(103)
            )
            DISTRIBUTED BY HASH(material_code) BUCKETS 10
            PROPERTIES (
                "replication_num" = "1"
            );""",
    "comments": {
        "table": "Stores the material data.",
        "columns": {},
    },
}
