"""
FactInvoiceSecondary Table Definition
Stores secondary invoice transaction data
"""

TABLE = {
    "order": 8,
    "name": "fact_invoice_secondary",
    "schema": """CREATE TABLE fact_invoice_secondary (
                active_flag SMALLINT,
                invoice_date INTEGER,
                customer_code INTEGER,
                cash_discount DOUBLE,
                cgst_amount DOUBLE,
                cgst_percentage DOUBLE,
                created_by_source VARCHAR(355),
                created_date INTEGER,
                creation_date_source INTEGER,
                customer_code_original INTEGER,
                updated_by_source VARCHAR(20),
                updation_date_source INTEGER,
                value DOUBLE,
                vat_amount DOUBLE,
                vat_percentage DOUBLE,
                volume DOUBLE,
                volume_in_kg DOUBLE,
                volume_in_ltr DOUBLE,
                year_month INTEGER,
                damage_quantity DOUBLE,
                darpan_ship_to_code VARCHAR(500),
                dealer_code VARCHAR(500),
                dealer_code_dp VARCHAR(180),
                dealer_sg_key VARCHAR(150),
                deleted_flag SMALLINT,
                discount_amount DOUBLE,
                division_code SMALLINT,
                foc_quantity DOUBLE,
                freight_amount DOUBLE,
                igst_amount DOUBLE,
                igst_percentage DOUBLE,
                invoice_date_df VARCHAR(150),
                invoice_no VARCHAR(150),
                invoice_print_number VARCHAR(160),
                item_code VARCHAR(200),
                item_determination_code VARCHAR(120),
                item_weight DOUBLE,
                load_flag VARCHAR(150),
                mfg_list_no VARCHAR(150),
                mis_type VARCHAR(150),
                mrp DOUBLE,
                net_weight_in_kg DOUBLE,
                order_no VARCHAR(200),
                print_date VARCHAR(150),
                printer_name VARCHAR(200),
                rate DOUBLE,
                receivable_date INTEGER,
                record_type VARCHAR(150),
                reporting_unit DOUBLE,
                reporting_unit_in_each DOUBLE,
                reporting_value DOUBLE,
                revised_net_value_msgvg DOUBLE,
                revised_net_value_mvg DOUBLE,
                route_code VARCHAR(150),
                route_name VARCHAR(200),
                sales_group_code SMALLINT,
                scheme_amount DOUBLE,
                sgst_amount DOUBLE,
                sgst_percentage DOUBLE,
                star_discount DOUBLE,
                stock_required_quantity DOUBLE,
                tcs_per DOUBLE,
                tcs_val DOUBLE,
                transfer_date INTEGER,
                tsi_code VARCHAR(150),
                tsi_name VARCHAR(200),
                type VARCHAR(355)
            )
            DISTRIBUTED BY HASH(customer_code) BUCKETS 20
            PROPERTIES (
                "replication_num" = "1"
            );""",
    "comments": {
        "table": "Stores secondary invoice transaction data.",
        "columns": {},
    },
    "indexes": {},
}
